### ISSUE TITLE
Why are there so many detection boxes in the detected image?

### ISSUE THREAD

**Issue by gm0515** [fizyr/keras-retinanet#851] opened 2018-12-25 07:03 UTC
We replace the resnet50 into the densenet121 as a front-end network for airplane-based identification. But in the final test, it was found that the entire image was full of detection boxes, which was very strange. Our test results are shown as follows:
![image](https://user-images.githubusercontent.com/39952480/50415140-6964ce80-0854-11e9-93e7-4cdec6171750.png)
There are no bugs in the training process, and we have trained 100,000 times based on this model.
The GPU we used is: GeForce GTX 1070 Ti.
We hope that you will reply to us, thank you very much.
Best regrads!

**Comment by hgaiser** [comment] 2018-12-25 08:44
As the densenet architecture is a community contribution, please try training on ResNet 50 using the COCO model as starting point. This will eliminate the possibility that densenet is causing your issue.

Also, what version of tensorflow / Keras are you using?

**Comment by hgaiser** [comment] 2018-12-26 10:13
Because we never used densenet, I know of ResNet that it is working as intended. Why do you want to use densenet ?

**Comment by hgaiser** [comment] 2019-01-02 09:05
Any progress on this?

**Comment by gm0515** [comment] 2019-01-07 11:14
I‘ll still try it. Anyway,thank you so much！

**Comment by hgaiser** [comment] 2019-01-24 08:42
I will close this for now then. Feel free to re-open if you have more information.

**Closed by hgaiser** 2019-01-24 08:42 UTC
