### ISSUE TITLE
Execution time of similar input size is much longer than 55ms

### ISSUE THREAD

**Issue by panda9095** [fizyr/keras-retinanet#91] opened 2017-11-22 03:31 UTC
Hi,

The model provided i.e., resnet50_coco_best_v1.2.0.h5, works pretty well for me, but I found the execution time is much longer than 55 ms mentioned in the README.

* INPUT: the input image is resized to  (600, 960, 3)
* GPU: 1 K80 is used.
*  Code Snapshot:
```python
for filename in filename_list:
    image = cv2.imread(filename)
    image = val_generator.preprocess_image(image)
    image, scale = val_generator.resize_image(image)
    start = time.time()
     _, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))
    print("processing time: ", time.time() - start)
```
* RUNNING TIME: The first execution is about 2.5 seconds, and the following executions are about 0.25 seconds. They area much more slower than 55 ms.

Would you kindly help me figure out what the problem could be? 
Thanks.

**Comment by hgaiser** [comment] 2017-11-22 07:38
We'll the 2.5s can be explained by the GPU needing to initialize it's state, so the first two or three detections can take a bit longer. After that it should be initialized and ready to go. The 55msec might be outdated, I haven't checked the times in a while and the architecture changed quite a bit since. Here are some of the times I'm seeing at the moment on COCO with a 1080ti:

```
0.074615478515625
0.07841849327087402
0.04439878463745117
0.15920305252075195
0.0550839900970459
0.06472539901733398
0.08249545097351074
0.08088874816894531
0.2203369140625
0.05638241767883301
0.07341122627258301
0.05973005294799805
0.05573725700378418
0.2079014778137207
0.06406116485595703
0.08787918090820312
0.0864863395690918
```

So on average it seems to be more around 80msec. It's strange that there are some outliers in this excerpt, can't really explain those.

As for the times you're seeing, the only explanation I can think of is that you're using a Kepler architecture GPU, which is quite a bit older from the Pascal architecture. The difference could be in there or perhaps in the version of CUDA/cuDNN/tensorflow that you're using (I'm using CUDA 9, cuDNN 7 and tensorflow 1.4).

**Comment by fangwudi** [comment] 2017-11-22 14:04
@panda9095 Would you please tell me where I can download 'resnet50_coco_best_v1.2.0.h5' you mentioned ?

**Comment by mkocabas** [comment] 2017-11-22 14:05
https://delftrobotics-my.sharepoint.com/personal/h_gaiser_fizyr_com/_layouts/15/guestaccess.aspx?docid=0cc7925c4f1154ddda5c5c3c088b8a147&authkey=AUySn3LkZtD4u7nq3viBMiQ&expiration=2017-12-16T15%3A15%3A32.000Z&e=914be80961224618b67321646495f497

**Comment by fangwudi** [comment] 2017-11-22 14:13
@mkocabas  thank you

**Comment by hgaiser** [comment] 2017-11-22 14:58
> @hgaiser
> Thanks for your reply.
> 
> Hardware solution. I tried running the same code on a Pascal architecture GPU (P4). The running time is about 0.16 second. It is still far away from 0.08 second.
> Software solution. The tensorflow 1.4 does not officially support CUDA 9, so I cannot test the performance. Would you kindly share an instruction on how to install tensorflow 1.4 compatible with CUDA9?
> Thanks.

On Arch the default is tensorflow 1.4 with CUDA 9. I cannot help you with installing that on your system.

**Comment by yhenon** [comment] 2017-11-22 15:19
Please report your cuDNN version, as it makes a significant difference in inference time.
I can confirm a runtime of around 60-80 milliseconds per image with tf 1.4, cuda 8.0, cudnn 6.0 on a Titan X.

Runtime on CPU for me is around 1.2s per image on a 12 core i7 (not that tf was not compiled locally, so no use of AVS and SSE4.

**Comment by panda9095** [comment] 2017-11-23 04:55
@yhenon 
Thanks.
My cuda is 8.0 and cudnn is 6, but my tf is 1.3. Though I upgraded tf to 1.4,  the running time does not decrease.

**Comment by exaltation** [comment] 2017-11-23 10:20
@panda9095 
I have cudnn 6.0, cuda 8.0, tensorflow 1.3, Titan X Pascal on Windows 10 and it reports ~10ms per image.

**Comment by hgaiser** [comment] 2017-11-24 09:36
After a discussion on Slack, it turned out that the confusion was that the first image(s) are slow because the GPU needs to be initialized. Closing this as it seems to be resolved.

**Closed by hgaiser** 2017-11-24 09:36 UTC
