### ISSUE TITLE
Timestamps before 1980

### ISSUE THREAD

**Issue by Cibale** [fizyr/keras-retinanet#200] opened 2017-12-20 14:27 UTC
When I try to deploy my code (which works perfectly on my local machine) I encounter this error:

```
...
2017-12-20 06:03:02,127 INFO - creating build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,129 INFO - copying keras_retinanet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,129 INFO - copying keras_retinanet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,130 INFO - copying keras_retinanet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,130 INFO - copying keras_retinanet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,130 INFO - copying keras_retinanet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,130 INFO - copying keras_retinanet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
2017-12-20 06:03:02,131 INFO - zip_safe flag not set; analyzing archive contents...
2017-12-20 06:03:02,132 INFO - keras_retinanet.bin.__pycache__.evaluate_coco.cpython-36: module references __file__
2017-12-20 06:03:02,133 INFO - keras_retinanet.bin.__pycache__.train.cpython-36: module references __file__
2017-12-20 06:03:02,141 INFO - creating 'dist/keras_retinanet-0.0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
2017-12-20 06:03:02,143 INFO - Traceback (most recent call last):
2017-12-20 06:03:02,144 INFO - File "setup.py", line 16, in <module>
2017-12-20 06:03:02,144 INFO - 'retinanet-evaluate-coco=keras_retinanet.bin.evaluate_coco:main',
2017-12-20 06:03:02,145 INFO - File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
2017-12-20 06:03:02,145 INFO - dist.run_commands()
2017-12-20 06:03:02,146 INFO - File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
2017-12-20 06:03:02,146 INFO - self.run_command(cmd)
2017-12-20 06:03:02,146 INFO - File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
2017-12-20 06:03:02,147 INFO - cmd_obj.run()
2017-12-20 06:03:02,147 INFO - File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
2017-12-20 06:03:02,148 INFO - self.do_egg_install()
2017-12-20 06:03:02,148 INFO - File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
2017-12-20 06:03:02,149 INFO - self.run_command('bdist_egg')
2017-12-20 06:03:02,149 INFO - File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
2017-12-20 06:03:02,149 INFO - self.distribution.run_command(command)
2017-12-20 06:03:02,149 INFO - File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
2017-12-20 06:03:02,150 INFO - cmd_obj.run()
2017-12-20 06:03:02,150 INFO - File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 231, in run
2017-12-20 06:03:02,150 INFO - dry_run=self.dry_run, mode=self.gen_header())
2017-12-20 06:03:02,150 INFO - File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 475, in make_zipfile
2017-12-20 06:03:02,151 INFO - visit(z, dirname, files)
2017-12-20 06:03:02,151 INFO - File "/usr/local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 468, in visit
2017-12-20 06:03:02,152 INFO - z.write(path, p)
2017-12-20 06:03:02,152 INFO - File "/usr/local/lib/python3.6/zipfile.py", line 1594, in write
2017-12-20 06:03:02,152 INFO - zinfo = ZipInfo.from_file(filename, arcname)
2017-12-20 06:03:02,152 INFO - File "/usr/local/lib/python3.6/zipfile.py", line 496, in from_file
2017-12-20 06:03:02,153 INFO - zinfo = cls(arcname, date_time)
2017-12-20 06:03:02,153 INFO - File "/usr/local/lib/python3.6/zipfile.py", line 338, in __init__
2017-12-20 06:03:02,153 INFO - raise ValueError('ZIP does not support timestamps before 1980')
2017-12-20 06:03:02,153 INFO - ValueError: ZIP does not support timestamps before 1980
2017-12-20 06:03:02,220 INFO - 
################################################################################
```

When I googled it, I learned that basically there are some files with wrong/broken timestamps (before 1980).

So, is it even possible to fix this?

**Comment by awilliamson** [comment] 2017-12-20 14:34
https://github.com/aws/aws-cli/issues/2639 Could be related? Definitely something I've not come across. Presuming aws deployment? I know a few others here use some AWS instances.

**Comment by Cibale** [comment] 2017-12-20 14:58
Indeed AWS deployment, but it's not because of some file which I created.

**Comment by de-vri-es** [comment] 2017-12-20 18:00
git does not apply modification times from the repository (if it even saves them). Additionally, given the fact that there are no files with old timestamps on your local machine, this strongly hints that the problem is with your employment environment.

Since it is not directly related to `keras-retinanet`, I'm closing this issue. If you find something in the repository causing the issue, feel free to leave a comment and we'll reopen this issue.

**Closed by de-vri-es** 2017-12-20 18:00 UTC
