### ISSUE TITLE
RetinaNet evaluation result subtle change

### ISSUE THREAD

**Issue by dwaithe** [fizyr/keras-retinanet#1015] opened 2019-05-24 16:39 UTC
Hi All,
I am very happy with the performance, but when I repeat the prediction, I get subtly different performance each time.  Below is four repeated predictions of 7 class dataset. I ran one after the other in the terminal. No changes in parameters or model. The AP can vary <0.03. Its small but I would expect this to be totally consistent. Any ideas?
Best,
Dominic.

2093 instances of class cell - neuroblastoma phalloidin with average precision: 0.8781
360 instances of class cell - erythroblast dapi with average precision: 0.9474
229 instances of class cell - c127 dapi with average precision: 0.9588
359 instances of class cell - eukaryote dapi with average precision: 0.9833
73 instances of class cell - fibroblast nucleopore with average precision: 0.9744
455 instances of class cell - hek peroxisome all with average precision: 0.7141
mAP using the weighted average of precisions among classes: 0.8819
mAP: 0.9093

2093 instances of class cell - neuroblastoma phalloidin with average precision: 0.8761
360 instances of class cell - erythroblast dapi with average precision: 0.9522
229 instances of class cell - c127 dapi with average precision: 0.9587
359 instances of class cell - eukaryote dapi with average precision: 0.9833
73 instances of class cell - fibroblast nucleopore with average precision: 0.9744
455 instances of class cell - hek peroxisome all with average precision: 0.7203
mAP using the weighted average of precisions among classes: 0.8820
mAP: 0.9108

2093 instances of class cell - neuroblastoma phalloidin with average precision: 0.8751
360 instances of class cell - erythroblast dapi with average precision: 0.9509
229 instances of class cell - c127 dapi with average precision: 0.9586
359 instances of class cell - eukaryote dapi with average precision: 0.9833
73 instances of class cell - fibroblast nucleopore with average precision: 0.9744
455 instances of class cell - hek peroxisome all with average precision: 0.7180
mAP using the weighted average of precisions among classes: 0.8810
mAP: 0.9100

2093 instances of class cell - neuroblastoma phalloidin with average precision: 0.8785
360 instances of class cell - erythroblast dapi with average precision: 0.9475
229 instances of class cell - c127 dapi with average precision: 0.9588
359 instances of class cell - eukaryote dapi with average precision: 0.9833
73 instances of class cell - fibroblast nucleopore with average precision: 0.9744
455 instances of class cell - hek peroxisome all with average precision: 0.7207
mAP using the weighted average of precisions among classes: 0.8830
mAP: 0.9105

**Comment by ceciliaAI** [comment] 2019-06-02 01:33
I would like to ask you how to do MAp after training with retinanet.

**Comment by hgaiser** [comment] 2019-06-06 08:15
@dwaithe did you use `evaluate.py` to get these results? What was the exact command?

**Comment by dwaithe** [comment] 2019-06-06 09:38
Thanks for your replies. Here is is the terminal command I used:

keras_retinanet/bin/evaluate.py csv  ../datasetpath/test_rn_n.csv ../datasetpath/retina_classes.csv /outputpah/resnet50_csv_50.h5 --convert-model

Running on Python 3.5.3, with Tensorflow: 1.4.1

**Comment by dwaithe** [comment] 2019-06-06 09:39
Is the generator still injecting variation between the samples as it would for training?

**Comment by hgaiser** [comment] 2019-06-07 07:32
Hmm that's quite an old tensorflow version, could you try updating it to at least 1.8? Preferably to 1.13? I don't know for certain if that is the issue, but it is worth a try.

> Is the generator still injecting variation between the samples as it would for training?

During evaluation the random behavior should be disabled.

**Comment by hgaiser** [comment] 2019-06-20 12:59
Closing, because this is probably a duplicate of https://github.com/fizyr/keras-retinanet/issues/1031 . Also, it is probably "resolved" with #1042 .

**Closed by hgaiser** 2019-06-20 12:59 UTC
