### ISSUE TITLE
Problem with image-max-side and image-min-side

### ISSUE THREAD

**Issue by angiebao** [fizyr/keras-retinanet#590] opened 2018-07-18 18:46 UTC
I have used debug.py and train.py to debug and train my model. One thing I found out is that even though I change the --image-min-side and --image-max-side argument, I still cannot get a better results in debug and train process. However, if I manually change my image to a particular size I preferred before feeding them into the program, the results is so much better.
I wonder how does the image-max-side and image-min-side works and how they related with width and height. Because sometimes I want my height larger than width and sometimes I want my width larger than height.

Thank you so much!

**Comment by hgaiser** [comment] 2018-07-19 08:07
You can check the implementation [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/image.py#L182). Basically it resizes such that the smalles side is equal to `image-min-side`. If after resizing the largest side is larger than `image-max-side`, it resizes down such that the largest side is equal to `image-max-side`. If you used our generators, then resizing it beforehand has no effect, as the generators resize as well.

Since this is not a bug, I'll close this issue. Please use Slack to ask questions like these.

**Closed by hgaiser** 2018-07-19 08:07 UTC

**Comment by makemate** [comment] 2018-11-19 22:57
Bounding boxes are rescaled in class Generator:  def preprocess_group_entry()
