### ISSUE TITLE
is it possible to make more than 300 detections?

### ISSUE THREAD

**Issue by apolanco3225** [fizyr/keras-retinanet#1218] opened 2019-12-13 01:29 UTC
So I've been using retinanet successfully but in my personal project I need to detect more than 300 objects and I seem to have a restriction here, is there any way I can achieve this using keras-retinanet? I've modified this file with no success 

keras-retinanet/keras_retinanet/layers/filter_detections.py 
![a](https://user-images.githubusercontent.com/16232171/70762247-ee731d00-1d1d-11ea-836f-5b9a1bd1b6d7.png)

Cheers wonderful people!

**Comment by snamjoshi** [comment] 2019-12-18 15:24
Isn't max detections a hyperparameter in `evaluate.py`? It seems you can set this as a flag when you run keras-retinanet in the CLI.

**Comment by hgaiser** [comment] 2019-12-19 09:19
Duplicate of https://github.com/fizyr/keras-retinanet/issues/1228

**Closed by hgaiser** 2019-12-19 09:19 UTC
