### ISSUE TITLE
Train resnet50 with CSV file

### ISSUE THREAD

**Issue by benjisympa** [fizyr/keras-retinanet#655] opened 2018-08-29 16:50 UTC
Hi,

I try to train a reset50 model with a CSV file, so I just use your train script like this : 
```
(py3.6) maurice@localhost:~/keras_retinanet/bin$ python train.py --imagenet-weights --epochs=3 --steps=1000 --freeze-backbone --image-min-side=224 --image-max-sid=224 csv ../../../annotations.csv ../../../class_mapping.csv --val-annotations=../../../val_annotations.csv
Using TensorFlow backend.
```

And I got this result that seems good : 
```
P4 (Conv2D)                     (None, None, None, 2 590080      P4_merged[0][0]                  
__________________________________________________________________________________________________
P5 (Conv2D)                     (None, None, None, 2 590080      C5_reduced[0][0]                 
__________________________________________________________________________________________________
P7 (Conv2D)                     (None, None, None, 2 590080      C6_relu[0][0]                    
__________________________________________________________________________________________________
anchors_0 (Anchors)             (None, None, 4)      0           P3[0][0]                         
__________________________________________________________________________________________________
anchors_1 (Anchors)             (None, None, 4)      0           P4[0][0]                         
__________________________________________________________________________________________________
anchors_2 (Anchors)             (None, None, 4)      0           P5[0][0]                         
__________________________________________________________________________________________________
anchors_3 (Anchors)             (None, None, 4)      0           P6[0][0]                         
__________________________________________________________________________________________________
anchors_4 (Anchors)             (None, None, 4)      0           P7[0][0]                         
__________________________________________________________________________________________________
regression_submodel (Model)     (None, None, 4)      2443300     P3[0][0]                         
                                                                 P4[0][0]                         
                                                                 P5[0][0]                         
                                                                 P6[0][0]                         
                                                                 P7[0][0]                         
__________________________________________________________________________________________________
anchors (Concatenate)           (None, None, 4)      0           anchors_0[0][0]                  
                                                                 anchors_1[0][0]                  
                                                                 anchors_2[0][0]                  
                                                                 anchors_3[0][0]                  
                                                                 anchors_4[0][0]                  
__________________________________________________________________________________________________
regression (Concatenate)        (None, None, 4)      0           regression_submodel[1][0]        
                                                                 regression_submodel[2][0]        
                                                                 regression_submodel[3][0]        
                                                                 regression_submodel[4][0]        
                                                                 regression_submodel[5][0]        
__________________________________________________________________________________________________
boxes (RegressBoxes)            (None, None, 4)      0           anchors[0][0]                    
                                                                 regression[0][0]                 
__________________________________________________________________________________________________
classification_submodel (Model) (None, None, 3)      2422555     P3[0][0]                         
                                                                 P4[0][0]                         
                                                                 P5[0][0]                         
                                                                 P6[0][0]                         
                                                                 P7[0][0]                         
__________________________________________________________________________________________________
clipped_boxes (ClipBoxes)       (None, None, 4)      0           input_16[0][0]                   
                                                                 boxes[0][0]                      
__________________________________________________________________________________________________
classification (Concatenate)    (None, None, 3)      0           classification_submodel[1][0]    
                                                                 classification_submodel[2][0]    
                                                                 classification_submodel[3][0]    
                                                                 classification_submodel[4][0]    
                                                                 classification_submodel[5][0]    
__________________________________________________________________________________________________
filtered_detections (FilterDete [(None, 300, 4), (No 0           clipped_boxes[0][0]              
                                                                 classification[0][0]             
==================================================================================================
Total params: 36,424,447
Trainable params: 12,863,295
Non-trainable params: 23,561,152
__________________________________________________________________________________________________
.local/lib/python3.6/site-packages/keras/callbacks.py:999: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
Epoch 1/3
 731/1000 [====================>.........] - ETA: 3:16 - loss: 3.0032 - regression_loss: 2.2995 - classification_loss: 0.7037
1000/1000 [==============================] - 725s 725ms/step - loss: 2.7359 - regression_loss: 2.1230 - classification_loss: 0.6129
288 instances of class ear with average precision: 0.2344
288 instances of class coin with average precision: 0.0933
7 instances of class hair with average precision: 0.0000
mAP: 0.1092

Epoch 00001: saving model to .snapshots/resnet50_csv_01.h5
Epoch 2/3
 599/1000 [================>.............] - ETA: 4:48 - loss: 1.6635 - regression_loss: 1.3325 - classification_loss: 0.3310
1000/1000 [==============================] - 717s 717ms/step - loss: 1.5815 - regression_loss: 1.2539 - classification_loss: 0.3277
288 instances of class ear with average precision: 0.3980
288 instances of class coin with average precision: 0.2752
7 instances of class hair with average precision: 0.0000
mAP: 0.2244

Epoch 00002: saving model to .snapshots/resnet50_csv_02.h5
Epoch 3/3
1000/1000 [==============================] - 714s 714ms/step - loss: 1.3707 - regression_loss: 1.0881 - classification_loss: 0.2827
288 instances of class ear with average precision: 0.6983
288 instances of class coin with average precision: 0.5762
7 instances of class hair with average precision: 0.0007
mAP: 0.4251

Epoch 00003: saving model to .snapshots/resnet50_csv_03.h5
```

When I load the model, I have : 
```
# adjust this to point to your downloaded/trained model
# models can be downloaded here: https://github.com/fizyr/keras-retinanet/releases
#model_path = 'small_last4-30epochsBoundingBox-inference.h5' #os.path.join('..', 'snapshots', 'resnet50_coco_best_v2.1.0.h5')
#model_path = 'resnet50_coco_best_v2.1.0.h5'
model_path = '.snapshots/resnet50_csv_03.h5'

# load retinanet model
model = models.load_model(model_path, backbone_name='resnet50')#'vgg16')

# if the model is not converted to an inference model, use the line below
# see: https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
#model = models.load_model(model_path, backbone_name='resnet50', convert=True)

print(model.summary())

# load label to names mapping for visualization purposes
#labels_to_names = {0: 'ear', 1: 'brass', 2: 'cooper', 3: 'euro1', 4: 'euro2'}
labels_to_names = {0: 'hair', 1: 'ear', 2: 'coin'}
```

and the result : 
```
...
P4 (Conv2D)                     (None, None, None, 2 590080      P4_merged[0][0]                  
__________________________________________________________________________________________________
P5 (Conv2D)                     (None, None, None, 2 590080      C5_reduced[0][0]                 
__________________________________________________________________________________________________
P7 (Conv2D)                     (None, None, None, 2 590080      C6_relu[0][0]                    
__________________________________________________________________________________________________
regression_submodel (Model)     (None, None, 4)      2443300     P3[0][0]                         
                                                                 P4[0][0]                         
                                                                 P5[0][0]                         
                                                                 P6[0][0]                         
                                                                 P7[0][0]                         
__________________________________________________________________________________________________
classification_submodel (Model) (None, None, 3)      2422555     P3[0][0]                         
                                                                 P4[0][0]                         
                                                                 P5[0][0]                         
                                                                 P6[0][0]                         
                                                                 P7[0][0]                         
__________________________________________________________________________________________________
regression (Concatenate)        (None, None, 4)      0           regression_submodel[1][0]        
                                                                 regression_submodel[2][0]        
                                                                 regression_submodel[3][0]        
                                                                 regression_submodel[4][0]        
                                                                 regression_submodel[5][0]        
__________________________________________________________________________________________________
classification (Concatenate)    (None, None, 3)      0           classification_submodel[1][0]    
                                                                 classification_submodel[2][0]    
                                                                 classification_submodel[3][0]    
                                                                 classification_submodel[4][0]    
                                                                 classification_submodel[5][0]    
==================================================================================================
Total params: 36,424,447
Trainable params: 12,863,295
Non-trainable params: 23,561,152
__________________________________________________________________________________________________
None
```

Next, I follow your notebook for prediction : 
```
# load image
image = read_image_bgr('testResnet50/ear/026_right_ear.jpg')

# copy to draw on
draw = image.copy()
draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)

# preprocess image for network
image = preprocess_image(image)
image, scale = resize_image(image)

print(scale)

# process image
start = time.time()
#boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
boxes, scores = model.predict_on_batch(np.expand_dims(image, axis=0))
print("processing time: ", time.time() - start)
print(boxes, scores)

# correct for image scale
boxes /= scale

# visualize detections
for box, score, label in zip(boxes[0], scores[0], labels[0]):
    # scores are sorted so we can break
    if score < 0.5:
        break
        
    color = label_color(label)
    
    b = box.astype(int)
    draw_box(draw, b, color=color)
    
    caption = "{} {:.3f}".format(labels_to_names[label], score)
    draw_caption(draw, b, caption)
    
plt.figure(figsize=(15, 15))
plt.axis('off')
plt.imshow(draw)
plt.show()
```
And I got : 
```
1.6260162601626016
processing time:  7.411804676055908
[[[ 0.12327076  0.04135071  0.00081436  0.14223127]
  [ 0.03122012  0.07056687  0.03280954  0.09889036]
  [ 0.14704604  0.05028684 -0.00227385  0.13829719]
  ...
  [-0.06273283 -0.06930423 -0.03109158 -0.02549179]
  [-0.08054096 -0.05832886 -0.05517679 -0.05201941]
  [-0.06409349 -0.02225551 -0.05245385 -0.03017061]]] [[[0.01062273 0.01114596 0.00996731]
  [0.01055735 0.01091804 0.01007619]
  [0.01060938 0.01086911 0.01023683]
  ...
  [0.01053495 0.01037296 0.00993317]
  [0.01063448 0.01058763 0.00995613]
  [0.01086705 0.01061296 0.01012373]]]
```

And I don't understand why all the boxes are near 0 pixels and why no classes are detect.

Do you know why ?

Thanks a lot.

**Comment by hgaiser** [comment] 2018-08-30 14:11
It seems you didn't convert your model to an inference model. You can do this once, or convert it while loading:

```python
# if the model is not converted to an inference model, use the line below
# see: https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
#model = models.load_model(model_path, backbone_name='resnet50', convert=True)
```

That commented part shows how to do it. It seems you ran into an issue with:

```python
#boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
```

And removed the `labels` output? The reason there are only 2 outputs is because these are the "raw" network outputs, namely the classification scores and regression values. The regression values still need to be applied to the anchors to form actual boxes, which is why they are close to 0.

If this solves your issue, please close the issue.

**Comment by hgaiser** [comment] 2018-09-03 19:45
I'm assuming the issue is resolved.

**Closed by hgaiser** 2018-09-03 19:45 UTC

**Comment by tonmoyborah** [comment] 2019-03-18 12:20
> #model = models.load_model(model_path, backbone_name='resnet50', convert=True)

it seems `load_model` doesn't take the convert argument now, does it?

**Comment by hgaiser** [comment] 2019-03-19 14:27
The argument got split into a [separate function](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/__init__.py#L86)
