### ISSUE TITLE
  from ..utils.compute_overlap import compute_overlap ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap

### ISSUE THREAD

**Issue by KwanjaiPSU** [fizyr/keras-retinanet#561] opened 2018-07-10 06:34 UTC
Hello all, plz help me....

**Comment by imransalam** [comment] 2018-07-10 12:03
Having the same issue

**Comment by tmontaigu** [comment] 2018-07-10 13:35
https://github.com/fizyr/keras-retinanet#faq

**Comment by yhenon** [comment] 2018-07-10 13:38
Indeed, and duplicate of #554

**Closed by yhenon** 2018-07-10 13:38 UTC
