### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by KwanjaiKJ** [fizyr/keras-retinanet#562] opened 2018-07-10 06:42 UTC
I don't know, where is error? plz help me again....
Epoch 1/50
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 483, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 478, in main
    callbacks=callbacks,
  File "/root/miniconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/root/miniconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/miniconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 287, in __next__
    return self.next()
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 295, in next
    group = self.groups[self.group_index]
IndexError: list index out of range

**Comment by hgaiser** [comment] 2018-07-12 07:36
Duplicate of https://github.com/fizyr/keras-retinanet/issues/567

**Closed by hgaiser** 2018-07-12 07:36 UTC
