### ISSUE TITLE
Running on Windows?

### ISSUE THREAD

**Issue by AdamMoses-GitHub** [fizyr/keras-retinanet#645] opened 2018-08-24 15:52 UTC
Is there a guide to running RetinaNet on Windows? I'm finding dependency conflicts, even when allowing configuration with Anaconda which usually resolves these.

**Comment by Miguel-P** [comment] 2018-08-30 13:51
The only dependency you need for running this on Windows is a C++ compiler that your python installation knows about. Try downloading Visual Studio Build tools 2015. If you have an up to date python version, then VS Build 2017 is fine as well. If you want to use any of the pre-trained COCO models or evaluate with the COCO evaluation criteria, you'll need to get pycocotools. The original makers won't provide support for windows, so install from this [fork](https://github.com/philferriere/cocoapi). I can confirm that train.py and evaulate.py etc. are all working fine with this set-up. 

If that helps solve your problem or if you've already solved it, then feel free to close this issue.

**Comment by hgaiser** [comment] 2018-08-30 14:17
We only really support Linux, and Windows specific support comes from the community. Since this is not an issue with the code I'll close it, please ask further instructions on the Slack channel, you might have a better chance there.

**Closed by hgaiser** 2018-08-30 14:17 UTC
