### ISSUE TITLE
How to find the   average recall  value,  , Because  the following command returns only the mAP

### ISSUE THREAD

**Issue by adeebakausar** [fizyr/keras-retinanet#1119] opened 2019-09-25 08:30 UTC
# To evaluate the model
!python3 keras_retinanet/bin/evaluate.py  csv test_labels.csv classes1.csv model.h5

**Comment by hgaiser** [comment] 2019-10-10 11:47
Duplicate of https://github.com/fizyr/keras-retinanet/issues/1128

**Closed by hgaiser** 2019-10-10 11:47 UTC
