### ISSUE TITLE
Some error with testing example

### ISSUE THREAD

**Issue by LinlyAC** [fizyr/keras-retinanet#197] opened 2017-12-19 14:09 UTC
Hello，I have a confused error when I use your  test code, ResNet50RetinaNet - COCO 2017.ipynb
![1](https://user-images.githubusercontent.com/16618172/34160663-c964b5fe-e508-11e7-8231-32a3bc3dba7a.png)
when I try to execute “from keras_retinanet.models.resnet import custom_objects”， it gives me an error.
![2](https://user-images.githubusercontent.com/16618172/34160704-fb42da1a-e508-11e7-9a0f-1ceeec607fe2.png)

**AttributeError: 'module' object has no attribute 'custom_objects'**

I don't know how to deal with this promblem. Can someone give me some advices?

**Comment by peterdudfield** [comment] 2017-12-19 15:49
See installation instructions,

**Comment by yhenon** [comment] 2017-12-19 22:11
duplicate of #92 #112 #73 (and maybe more). Please read the installation instructions.

**Closed by yhenon** 2017-12-19 22:11 UTC

**Comment by muhammetp** [comment] 2018-07-31 08:29
i have implemented pip install --user --upgrade keras-retinanet that command but i still get the error ImportError: cannot import name custom_objects. i have used the macos and python 2.7. here is what written when i execute the command

pip install --user --upgrade keras-retinanet
Requirement already up-to-date: keras-retinanet in /Users/muhammet.pakyurek/Library/Python/2.7/lib/python/site-packages (0.4.1)
Requirement already satisfied, skipping upgrade: keras-resnet in /Users/muhammet.pakyurek/Library/Python/2.7/lib/python/site-packages (from keras-retinanet) (0.1.0)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python2.7/site-packages (from keras-retinanet) (1.11.0)
Requirement already satisfied, skipping upgrade: cython in /Users/muhammet.pakyurek/Library/Python/2.7/lib/python/site-packages (from keras-retinanet) (0.28.4)
Requirement already satisfied, skipping upgrade: keras in /usr/local/lib/python2.7/site-packages (from keras-retinanet) (2.2.2)
Requirement already satisfied, skipping upgrade: scipy in /usr/local/lib/python2.7/site-packages (from keras-retinanet) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (1.15.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing==1.0.2 in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (1.0.2)
Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (2.8.0)
Requirement already satisfied, skipping upgrade: keras-applications==1.0.4 in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (1.0.4)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python2.7/site-packages (from keras->keras-retinanet) (3.13)
