### ISSUE TITLE
Error when running train_coco.py

### ISSUE THREAD

**Issue by mukherjees** [fizyr/keras-retinanet#129] opened 2017-11-30 19:19 UTC
(TensorFlow 1.4.0, Python 3.6.3): `python example/train_coco.py <path/to/COCO>` yields the following error:
~~~~
  optimizer=keras.optimizers.adam(lr=1e-5, clipnorm=0.001)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 206, in __next__
    return self.next()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 217, in next
    return self.compute_input_output(group)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/utils/image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "examples/train_coco.py", line 111, in <module>
    keras_retinanet.callbacks.coco.CocoEval(val_generator),
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
StopIteration
~~~~

I suspect the problem is in utils/image.py in the line
~~~~
[i, j] = np.where(mask == 255)
~~~~
where, for some reason, `j` happens to be empty.

**Comment by alexiskattan** [comment] 2017-11-30 20:01
Did you update to the latest version of the code (~past few hours)? @hgaiser  pushed a fix #126.  However, I too am still getting the error.

**Comment by hgaiser** [comment] 2017-11-30 21:30
Did you `pip install` the older version? Try running your training command with the prefix `PYTHONPATH=/path/to/keras-retinanet`.

**Comment by zrachlin** [comment] 2017-11-30 23:15
@hgaiser I think that when looking at the code anywhere outside of github, the two empty lines in the copyright get automatically removed, so the line in question is actually 78, not 76. So error is happening here:
boxes[index, 0] = float(min(j)) 

I'm having the same problem

Epoch 1/20
1385/1386 [============================>.] - ETA: 0s - loss: 0.6965 - regression_loss: 0.0011 - classification_loss: 0.6955Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "/data/home/zrachlin/.local/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 206, in __next__
    return self.next()
  File "/data/home/zrachlin/.local/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 217, in next
    return self.compute_input_output(group)
  File "/data/home/zrachlin/.local/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "/data/home/zrachlin/.local/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "/data/home/zrachlin/.local/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/utils/image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))

**Comment by mukherjees** [comment] 2017-11-30 23:27
Thanks for your comments, @alexiskattan  and @hgaiser .  Indeed, just after I submitted the issue, I realized that there was a newer version of the code in utils/image.py (and in preprocessing/coco.py).  After updating the code to the newest version, `python train_coco.py <path/to/COCO>` seems to be running satisfactorily, without crashes.

As for @alexiskattan and @zrachlin seeing the same problem even after updating the code to the newest version, I am afraid I cannot provide any information because for me, updating the code to the newest version did the job.

**Comment by alexiskattan** [comment] 2017-11-30 23:31
Can confirm it works now!  I had to do some weird uninstall/reinstall because of anaconda but it does work.  Thank you.

**Comment by hgaiser** [comment] 2017-12-01 07:32
> @hgaiser I think that when looking at the code anywhere outside of github, the two empty lines in the copyright get automatically removed, so the line in question is actually 78, not 76.

Hmm I'm a bit skeptical about this, can you provide evidence for this?

Other than that, this issue appears to be resolved so I'll close it.

**Closed by hgaiser** 2017-12-01 07:32 UTC

**Comment by zrachlin** [comment] 2017-12-01 19:16
@alexiskattan Did you uninstall/reinstall in any particular way that was different from the readme? I can't seem to get past this error- i've uninstalled/reinstalled 5 times now with no progress.

**Comment by hgaiser** [comment] 2017-12-01 19:20
Check your error and the file it says the error came from (judging by your earlier post, `/data/home/zrachlin/.local/lib/python3.6/site-packages/keras_retinanet-0.0.1-py3.6.egg/keras_retinanet/utils/image.py`) and check if the changes from https://github.com/fizyr/keras-retinanet/commit/0e255e08b2fa8a6ec1b797c41677a984e27609bd are in that file. If they're not, you're running an outdated version and you need to update somehow. Can't really help you much more.
