### ISSUE TITLE
More gpus, training problems.

### ISSUE THREAD

**Issue by wgshun** [fizyr/keras-retinanet#84] opened 2017-11-21 11:30 UTC
In the `train_csv.py`， i wrote  `os.environ["CUDA_VISIBLE_DEVICES"]="0, 1"`
but,
```
Tue Nov 21 19:27:15 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:01:00.0      On |                  N/A |
| 52%   70C    P2   154W / 230W |   7909MiB /  8110MiB |     93%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    Off  | 0000:02:00.0     Off |                  N/A |
|  0%   48C    P8    15W / 230W |   7712MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1117    G   /usr/lib/xorg/Xorg                              93MiB |
|    0      1657    G   compiz                                          51MiB |
|    0     13092    C   python                                        7760MiB |
|    1     13092    C   python                                        7709MiB |
+-----------------------------------------------------------------------------+
```

What is the problem ?

**Comment by de-vri-es** [comment] 2017-11-21 12:29
If you have issues with `keras` please use the related channels for support. This repository is about `keras-retinanet`. Your issue seems to be with either keras, tensorflow or cuda itself.

Additionally, it is quite hard to see from your issue what your problem really is. You're just quoting one line of code and the output of a tool.

When reporting an issue please be clear what you would expect to happen and what happens instead. Include steps to reproduce the issue. When possible, do add logs and/or the output of tools as proof of the wrong behaviour


--- 

All that being said, you should probably set the environment *before* importing keras. Your best bet would be to set the environment variables outside of the python script.  If that doesn't work, please use the appropriate channels for resolving your issue further.

**Closed by de-vri-es** 2017-11-21 12:29 UTC

**Comment by hgaiser** [comment] 2017-11-21 12:38
I also remember a bug in I believe keras 2.0.9 which caused it to "claim" all GPU's regardless of your environment settings. If this is an issue for you, try the `master` branch of keras.

**Comment by wgshun** [comment] 2017-11-22 04:00
Thanks.
