### ISSUE TITLE
PASCAL VOC and validation

### ISSUE THREAD

**Issue by Shiro-LK** [fizyr/keras-retinanet#501] opened 2018-06-12 08:15 UTC
Hello,

I am trying to train PASCAL VOC 2007 and PASCAL VOC 2012 on retinanet with resnet50 as backbone. the best result I get is 66 map (on pascal voc test 2007). Did anyone get better results  ?  I trained using imagenet weights.

**Comment by hgaiser** [comment] 2018-06-12 08:20
Thanks for checking out keras-retinanet. Although since this is not an actual issue with the code, I'm going to close it. Discussions like this are best kept on the slack channel. Unless of course you have an idea of an issue in your situation. Personally I've never trained Pascal VOC on keras-retinanet and I don't know many people that did.

**Closed by hgaiser** 2018-06-12 08:20 UTC

**Comment by dby2017** [comment] 2018-12-10 12:41
The best result I get is 64 mAp.

**Comment by qihaouu** [comment] 2019-01-03 03:45
I get the best result is 66 too, have u know what the issue is?

**Comment by qihaouu** [comment] 2019-01-03 06:54
> The best result I get is 64 mAp.

have u find the reason？

**Comment by dby2017** [comment] 2019-01-03 07:52
> > The best result I get is 64 mAp.
> 
> have u find the reason？

I don't find the reason.
