### ISSUE TITLE
Error when running the example on Pascal VOC 2012

### ISSUE THREAD

**Issue by ssoulhi** [fizyr/keras-retinanet#114] opened 2017-11-28 15:05 UTC
Hi,

I got this error when trying to train on Pascal VOC 2012.  Note I did not try on VOC 2007 since I did not find it. It looks they have same structure. Note that the test.txt file is not in VOC 2012

Epoch 1/50
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-08a2eaa377b8> in <module>()
      9     callbacks=[
     10         keras.callbacks.ModelCheckpoint('snapshots/resnet50_voc_2007.h5', monitor='val_loss', verbose=1, save_best_only=True),
---> 11         keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
     12     ],
     13 )

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2112                     outs = self.train_on_batch(x, y,
   2113                                                sample_weight=sample_weight,
-> 2114                                                class_weight=class_weight)
   2115 
   2116                     if not isinstance(outs, list):

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in train_on_batch(self, x, y, sample_weight, class_weight)
   1824             sample_weight=sample_weight,
   1825             class_weight=class_weight,
-> 1826             check_batch_axis=True)
   1827         if self.uses_learning_phase and not isinstance(K.learning_phase(), int):
   1828             ins = x + y + sample_weights + [1.]

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1409                                     output_shapes,
   1410                                     check_batch_axis=False,
-> 1411                                     exception_prefix='target')
   1412         sample_weights = _standardize_sample_weights(sample_weight,
   1413                                                      self._feed_output_names)

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    151                             ' to have shape ' + str(shapes[i]) +
    152                             ' but got array with shape ' +
--> 153                             str(array.shape))
    154     return arrays
    155 

ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 90360, 24)

**Comment by yhenon** [comment] 2017-11-28 15:07
duplicate of #88

**Comment by yhenon** [comment] 2017-11-28 15:11
duplicate of #88

**Closed by yhenon** 2017-11-28 15:11 UTC

**Comment by ssoulhi** [comment] 2017-11-28 15:31
I don't think it's same issue as #88 since my keras version is 2.1.1

**Comment by hgaiser** [comment] 2017-11-28 15:44
You need Keras 2.0.9 though (or `master`). Also, is your `keras-retinanet` up-to-date? Judging by the name of the model, it seems outdated? Or did you change some stuff manually?
