### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by Tangzixia** [fizyr/keras-retinanet#619] opened 2018-08-02 14:51 UTC
when I download the project and want to run this code in my workstation, it report   this problem:ImportError: keras_retinanet/bin/../../keras_retinanet/utils/compute_overlap.so: undefined symbol: _Py_ZeroStruct?
Thank you for your advice!Thank you!!!

**Comment by hgaiser** [comment] 2018-08-03 10:38
Did you perhaps copy the repository from one machine to another? It's a wild guess, but it seems like your compute_overlap.so is not proper. You could try deleting `keras_retinanet/bin/../../keras_retinanet/utils/compute_overlap.so` and re-run `python setup.py build_ext --inplace`?

**Comment by Tangzixia** [comment] 2018-08-06 02:18
Thank you very much, finally I find the reason is because the problem is result from different python version, but I have another problem whether the size of my datasets is 1000*800*3? If the size of my datasets is 512*512, the parameters of train.py such as image-min-size and image-max-size, how to set this? I'm looking forward to your reply, thanks again for your taking time out of your busy schedule!

**Comment by hgaiser** [comment] 2018-08-07 21:26
You could try setting them to 512x512, you could leave them as is or you could set any other value, that's up to you. But do check using debug.py to see if your data is still trainable.

Closing this as the issue is resolved.

**Closed by hgaiser** 2018-08-07 21:26 UTC

**Comment by dskilling77** [comment] 2019-07-31 13:48
Tangzixia, how did you solve your "undefined symbol: _Py_ZeroStruct" issue? I know you said it was a version issue, but i'm having the same issue and re-building/installing isn't fixing it.

**Comment by lalonderodney** [comment] 2019-10-22 16:35
Try this solution, it worked for me if you're using python 3 (`python3 setup.py build_ext --inplace`)
https://github.com/cocodataset/cocoapi/issues/90#issuecomment-360302008
