### ISSUE TITLE
Import Keras from Tensorflow to Prevent Issues?

### ISSUE THREAD

**Issue by orcaman** [fizyr/keras-retinanet#1115] opened 2019-09-20 06:37 UTC
Hi team,

Per this issue: https://github.com/keras-team/keras/issues/12379

The library doesn't work when using TF 2.0. Replacing the imports of `from keras import backend` to `from tensorflow.keras import backend` seems to solve the issue.

Loading Keras from TF seems like a good idea for better compatibility with TF (as this library is coupled with TF anyway I don't think it's a problem).

**Comment by TimbusCalin** [comment] 2019-09-21 11:55
Hi Orcaman. So did you manage to replace each keras import with tensorflow.keras and all the code worked?

**Comment by orcaman** [comment] 2019-09-22 19:09
No, I've edited the source on an internal project, didn't try to replace all occurrences

**Comment by hgaiser** [comment] 2019-09-26 12:23
Closing as duplicate of https://github.com/fizyr/keras-retinanet/issues/1117

**Closed by hgaiser** 2019-09-26 12:23 UTC
