### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HuangQinJian** [fizyr/keras-retinanet#930] opened 2019-03-05 12:34 UTC
keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:170: UserWarning: Image with id 244 (shape (466, 542, 3)) contains the following invalid boxes: [[430. 183. 595. 285.]].
  annotations['bboxes'][invalid_indices, :]
keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:170: UserWarning: Image with id 1033 (shape (465, 1083, 3)) contains the following invalid boxes: [[451. 444. 518. 489.]
 [454. 477. 519. 561.]].
  annotations['bboxes'][invalid_indices, :]
keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:170: UserWarning: Image with id 896 (shape (400, 527, 3)) contains the following invalid boxes: [[495. 426. 622. 552.]].
  annotations['bboxes'][invalid_indices, :]
keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:170: UserWarning: Image with id 1100 (shape (527, 520, 3)) contains the following invalid boxes: [[406. 344. 634. 426.]
 [523. 405. 594. 535.]
 [105. 418. 197. 539.]
 [345. 470. 522. 507.]].

What does it mean?

**Comment by hgaiser** [comment] 2019-03-05 12:39
It means your dataset contains bounding boxes that lie outside the image. Your first warning for instance has `x2 = 595` but your width of your image is `542`.

Since this is not an issue with our code, I'll close this. Please continue the discussion on Slack.

**Closed by hgaiser** 2019-03-05 12:39 UTC

**Comment by HuangQinJian** [comment] 2019-03-05 13:11
I have a question.The origin image size was   (466, 542, 3), but I want to scale it to(800,600,3),so I aslo rescaled the box?It is wrong?Or the input size can be random?Or where can I set the input_size?

**Comment by hgaiser** [comment] 2019-03-05 13:13
You can set the [`image-min-side` and `image-max-side`](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L409-L410) arguments in train.py. This will automatically scale your images and bboxes accordingly.

**Comment by HuangQinJian** [comment] 2019-03-05 13:14
So ,I do not need to sacle box in annotations.csv?

**Comment by SalahAdDin** [comment] 2020-01-28 12:34
@hgaiser Is there a way to know which image is the problematic one? I tried looking by the boxes but i didn't find any box in my dataset matched with.

**Comment by hgaiser** [comment] 2020-01-30 08:38
If you have the generator, you can get the image path using `generator.image_path(image_index)`.

**Comment by SalahAdDin** [comment] 2020-01-30 12:00
We are gettıng thıs warnıng whıle we are training, how can we get the generator then?

**Comment by hgaiser** [comment] 2020-01-30 12:09
You can check in `train.py` how the generators are created and create an identical one, or change the code in the generator where this warning is printed to also print the path of the image file. Note that this wasn't possible when the warning was first created, because the `image_path` method didn't exist back then. If you want, a PR to change the text message to include the image path could be useful.

**Comment by SalahAdDin** [comment] 2020-01-30 12:21
@hgaiser , i will work on this.

**Comment by SalahAdDin** [comment] 2020-01-31 13:38
@hgaiser Why are you reducing by -1 al values in annotations? I modified my VOC converter to get the max value over the annotation and 0, getting most of this values in 0, and the PASCAL VOC generator file still reduces this values by one, why?

**Comment by hgaiser** [comment] 2020-02-03 08:42
If I recall correctly, the Pascal dataset has indices 1-based, like in Matlab. We use python / numpy so it is 0-based.

**Comment by SalahAdDin** [comment] 2020-02-03 09:21
@hgaiser Yeah, i don't get you.

**Comment by hgaiser** [comment] 2020-02-03 09:24
The top left corner of an image in Matlab has coordinates `(1, 1)`. The top left corner of a matrix in numpy has coordinates `(0, 0)`. The annotations in Pascal VOC are in Matlab coordinates.

**Comment by SalahAdDin** [comment] 2020-02-03 09:33
Yes, i understand that, but, for example, in my converter script i had to add:
```
                ET.SubElement(bbox, 'xmin').text = str(max(xmin,1.1))
                ET.SubElement(bbox, 'ymin').text = str(max(ymin,1.1))
                ET.SubElement(bbox, 'xmax').text = str(min(xmax,width))
                ET.SubElement(bbox, 'ymax').text = str(min(ymax,height))
```

Why? Because the PASCAL VOC script reduces the minimum values in one, so, if i get the max between mins and 0, it will be 0, and the script will also reduce that value to -1, making that box in a wrong box.

Did i make me understand?

**Comment by hgaiser** [comment] 2020-02-03 09:58
But then it seems that your data is formatted like Pascal VOC, but the top left coordinate is `(0, 0)`. Is this true?

**Comment by SalahAdDin** [comment] 2020-02-03 10:00
Well, i am not sure actually. But we can say "yes": https://github.com/thsant/wgisd/issues/1

**Comment by hgaiser** [comment] 2020-02-03 10:09
I see. But the original Pascal VOC dataset has `(1, 1)` as the top-left corner, and that is what this generator is intended for. My advise: don't use Pascal VOC data format. It is kinda bad. It is easier to use the CSV generator in my opinion.

**Comment by SalahAdDin** [comment] 2020-02-03 10:17
@hgaiser, do you have an example of that?

On the other hand, the [AFCR](http://data.acfr.usyd.edu.au/ag/treecrops/2016-multifruit/) dataset is still using a VOC format, but with different parameters.

**Comment by hgaiser** [comment] 2020-02-03 10:38
An example of the CSV dataset? You can find it [here](https://github.com/fizyr/keras-retinanet#csv-datasets).

**Comment by SalahAdDin** [comment] 2020-02-03 10:49
Well, the problem is they are using custom coordinates: normalized values, radius, differences, etc. That's why I'm converting them.
