### ISSUE TITLE
UserWarning Invalid boxes

### ISSUE THREAD

**Issue by awilliamson** [fizyr/keras-retinanet#164] opened 2017-12-06 11:14 UTC
@hgaiser With the recent Multi-GPU PR code #111 I tried retraining coco. I had successfully been training for 30 or so epochs for the past day on pre-PR code. However, now when training with the same dataset location it produces invalid indices warnings.

Command:
`env CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 PYTHONPATH=./ python scripts/train.py --multi-gpu=8 --batch-size=8 coco ./data/coco` GPUs are Titan XPs.

Error:
```
/home/ashley/GitHubTests/keras-retinanet/keras_retinanet/preprocessing/generator.py:100: UserWarning: Image with id 70694 (shape (480, 640, 3)) contains the following invalid boxes: [array([ 488.63,    2.16,  640.  ,  305.26,    0.  ]), array([ 500.59,  194.87,  640.  ,  347.45,   65.  ])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
/home/ashley/GitHubTests/keras-retinanet/keras_retinanet/preprocessing/generator.py:100: UserWarning: Image with id 70696 (shape (480, 640, 3)) contains the following invalid boxes: [array([ 113.26,  174.92,  545.15,  480.  ,   20.  ])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
/home/ashley/GitHubTests/keras-retinanet/keras_retinanet/preprocessing/generator.py:100: UserWarning: Image with id 70704 (shape (480, 640, 3)) contains the following invalid boxes: [array([ 409.81,  312.77,  640.  ,  474.84,   57.  ])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
/home/ashley/GitHubTests/keras-retinanet/keras_retinanet/preprocessing/generator.py:100: UserWarning: Image with id 70707 (shape (480, 640, 3)) contains the following invalid boxes: [array([ 489.83,  316.37,  640.  ,  463.4 ,    8.  ])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
/home/ashley/GitHubTests/keras-retinanet/keras_retinanet/preprocessing/generator.py:100: UserWarning: Image with id 70729 (shape (480, 640, 3)) contains the following invalid boxes: [array([ 623.31,  110.84,  640.  ,  119.83,    8.  ])].
  [annotations[invalid_index, :] for invalid_index in invalid_indices]
```
The Training progress bar continues amongst all of that, a bit hard to capture.

Has any modification of dataset preprocessing been altered from the original code? I understand that the generators were condensed into a single location. I was wanting to test the GPU training the other day, but active development was underway so I waiting; apologies for not spotting this sooner.

Any idea what is at fault here? Or is this a case of UserWarnings which can be safely ignored?

**Comment by hgaiser** [comment] 2017-12-06 12:12
Thanks for reporting this, seems the check for invalid annotations was a bit too tight. It is supposed to ignore images outside of the image bounds, but the annotations you mention are right on that bound (which should be okay). Commit https://github.com/fizyr/keras-retinanet/commit/5849cfe63be12dc9826390e6ef971e8e7e2a1eac should fix this, can you try and verify that the issue is resolved?

ps. the warning means it will delete those annotations from the list of annotations, so it is "safe" to continue, it will just ignore a small portion of the training data.

**Comment by awilliamson** [comment] 2017-12-06 13:12
Went and looked at the line responsible for the warnings. Noticed that it does indeed ignore them as you say. I ended up just doing `warnings.filterwarnings("ignore")` in train.py as it was hard to see progress.
Updated to master, and re-ran, I don't see any UserWarnings. Going to assume it is fixed for now. This is a multi-gpu run example too fyi.

**Comment by hgaiser** [comment] 2017-12-06 13:20
Alright, awesome. Judging by the warnings you showed, the commit would fix it indeed.

Closing this issue then.

**Closed by hgaiser** 2017-12-06 13:20 UTC

**Comment by juanmanuellopezcorrea** [comment] 2021-12-03 10:23
Hello everyone, I have the same problem with -- gpu. 
 !keras_retinanet/bin/train.py --freeze-backbone --tensorboard-dir "/content/drive/MyDrive/TomatoDeep/"  --gpu 0 --weights "/content/drive/MyDrive/TomatoDeep/keras-retinanet/snapshots/resnet50_coco_best_v2.1.0.h5" --batch-size 32 --snapshot-path "/content/drive/MyDrive/TomatoDeep/keras-retinanet/snapshots/" --steps 50 --epochs 100 csv '/content/drive/MyDrive/TomatoDeep/train/annotations.csv' '/content/drive/MyDrive/TomatoDeep/train/classes.csv'



The annotations are correct in the csv but  I get this error:

keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py:181: UserWarning: Image /content/drive/MyDrive/TomatoDeep/train/almacen/IMG_4466.JPG with id 532 (shape (3888, 5184, 3)) contains the following invalid boxes: [[3170. 4101. 3589. 4890.]
 [2072. 4784. 2458. 5184.]
 [3524. 4869. 3888. 5184.]
 [ 597. 4912. 1096. 5184.]].
  annotations['bboxes'][invalid_indices, :]

But you can see Bounding Boxes coordinates are correct  with the shape image. I dont know what is the problem
