### ISSUE TITLE
Training with less resolution doesn't improve inference time ?? 

### ISSUE THREAD

**Issue by scstu** [fizyr/keras-retinanet#1053] opened 2019-06-29 13:40 UTC
I have trained  my model with the default configuration using :

```
ResNet50
--image-min-side = 800
--image-max-side = 1333
```
I got `0.14s` as inference time 
I wanted to improve that results ( even if I am sacrificing the poor performance). so I reduce the resolution during training : 
```
--image-min-side = 500
--image-max-side = 500
```
but didn't get any improvements in inference time 
what I am doing wrong ? any advice will be appreciated!

**Comment by scstu** [comment] 2019-07-01 05:04
Any Help lease ?

**Comment by hgaiser** [comment] 2019-07-03 09:35
Closing as this is (most likely) not an issue with the code. Please use the keras-retinanet Slack channel for usage questions.

That said; did you also reduce the image during inference?

**Closed by hgaiser** 2019-07-03 09:35 UTC

**Comment by scstu** [comment] 2019-07-18 11:36
I am reopening this issue as I think there is something wrong I am doing or the code has to be changed in somehow! 
Retinanet has been trained in the original paper with 5 different scales [400 - 800] for each model {Resnet 50 and Resnet 101}. here are the results :

![1](https://user-images.githubusercontent.com/38878761/61453348-71bb5d00-a990-11e9-8dba-ed2d2fe62de5.JPG)

as clearly can be observed from their results that the **mAP** decreases significantly when decreasing the scale as well as **the processing time** 

I did exactly what they did (Train RetinaNet-50 on my dataset with 5 different scales) 
![mine](https://user-images.githubusercontent.com/38878761/61453546-fdcd8480-a990-11e9-98e1-cfcdbfeb38b6.JPG)

However, I got the same processing time each time (or slightly different). I used the following command to evaluate the model on my dataset and getting the processing time : 

`keras_retinanet/bin/evaluate.py --convert-model csv ./test_labels.csv labels.csv ./snapshots/resnet50_csv_45.h5`  
 I have asked everywhere but couldn't get any answer.

 any help or suggestions will be appreciated, Thank you.

**Comment by hgaiser** [comment] 2019-07-18 11:59
You need to pass the same `--image-min-side` and `--image-max-side` to the evaluate command.

**Comment by yleo** [comment] 2020-01-17 12:36
I have exactely the same issue than @scstu.

@hgaiser, what you propose cannot answer to the question as the code is applying min_side and then if the new max side of the image is greater than max_side, there is a second step.

Yet, the issue is that if we reduce drastically the size of the training images such as min_side = 200 instead of 1000, the prediction speed is the same. In my case, I made the same transformation for test images before to predict.

Any idea ?

Related code:

```
def compute_resize_scale(image_shape, min_side=800, max_side=1333):
    """ Compute an image scale such that the image size is constrained to min_side and max_side.
    Args
        min_side: The image's min side will be equal to min_side after resizing.
        max_side: If after resizing the image's max side is above max_side, resize until the max side is equal to max_side.
    Returns
        A resizing scale.
    """
    (rows, cols, _) = image_shape

    smallest_side = min(rows, cols)

    # rescale the image so the smallest side is min_side
    scale = min_side / smallest_side

    # check if the largest side is now greater than max_side, which can happen
    # when images have a large aspect ratio
    largest_side = max(rows, cols)
    if largest_side * scale > max_side:
        scale = max_side / largest_side

    return scale
```
Best wishes,
Yannick

**Comment by hgaiser** [comment] 2020-01-20 09:33
> @hgaiser, what you propose cannot answer to the question as the code is applying min_side and then if the new max side of the image is greater than max_side, there is a second step.

I proposed that solution because in the call to `retinanet-evaluate` @scstu didn't pass any `image-min-side` nor `image-max-side`. What is the code you used to measure the time? Did you ensure the images were resized as you expect? Maybe add print statements to print the shape of the images before passing it through the network.
