### ISSUE TITLE
Segmentation Fault when Testing Sample

### ISSUE THREAD

**Issue by jlarochewpi** [fizyr/keras-retinanet#412] opened 2018-04-19 18:26 UTC
This is based off of the code given in the Notebook ( https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb )

When the code gets to the following line:

`keras.backend.tensorflow_backend.set_session(get_session())`

The system has a segmentation fault.
The output is this:
`Using Tensorflow backend.
Segmentation fault (core dump)`

Initially assuming it was a memory error, I modifed the get_session function as follows:

`def get_session():`
`    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = 0.2) #I have tried from 0.1 to 0.9, the issue is still the same`
`    config = tf.ConfigProto()
`    config.gpu_options.allow_growth = True`
`    return tf.Session(config=config)`

Thanks in advance

**Comment by yhenon** [comment] 2018-04-19 22:04
This code base is pure python so the segfault is not a responsibility of the code contained here. Check your dependencies are installed correctly. 
Duplicate of #188, you can have a look there for more information.

**Closed by yhenon** 2018-04-19 22:04 UTC
