### ISSUE TITLE
Installation issue (in step 3)

### ISSUE THREAD

**Issue by YitzhakSp** [fizyr/keras-retinanet#108] opened 2017-11-26 10:44 UTC
Hi. When running step 3 of the installation
```
pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet
```
i get the error
```
Collecting git+https://github.com/broadinstitute/keras-resnet
  Cloning https://github.com/broadinstitute/keras-resnet to c:\users\yitzhak\appdata\local\temp\pip-m1_9x8_j-build
Requirement already up-to-date: keras in c:\users\yitzhak\anaconda3\lib\site-packages (from keras-resnet==0.0.8)
Requirement already up-to-date: pyyaml in c:\users\yitzhak\anaconda3\lib\site-packages (from keras->keras-resnet==0.0.8)
Collecting numpy>=1.9.1 (from keras->keras-resnet==0.0.8)
  Downloading numpy-1.13.3-cp36-none-win_amd64.whl (13.1MB)
Collecting scipy>=0.14 (from keras->keras-resnet==0.0.8)
  Downloading scipy-1.0.0-cp36-none-win_amd64.whl (30.8MB)
Requirement already up-to-date: six>=1.9.0 in c:\users\yitzhak\anaconda3\lib\site-packages (from keras->keras-resnet==0.0.8)
Installing collected packages: keras-resnet, numpy, scipy
  Found existing installation: keras-resnet 0.0.8
    Uninstalling keras-resnet-0.0.8:
      Successfully uninstalled keras-resnet-0.0.8
  Running setup.py install for keras-resnet: started
    Running setup.py install for keras-resnet: finished with status 'done'
Exception:
Traceback (most recent call last):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2756, in get_entry_map
    ep_map = self._ep_map
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2727, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\setuptools\dist.py", line 336, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 735, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2759, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2489, in parse_map
    for group, lines in data:
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 3086, in split_sections
    for line in yield_lines(s):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2349, in yield_lines
    for ss in strs:
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2684, in _get_metadata
    if self.has_metadata(name):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1481, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1841, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1721, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1661, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Yitzhak\\AppData\\Roaming\\Python\\Python36\\site-packages\\keras_resnet-0.0.8-py3.6.egg'
Traceback (most recent call last):
  File "C:\Users\Yitzhak\Anaconda3\Scripts\pip-script.py", line 5, in <module>
    sys.exit(pip.main())
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\__init__.py", line 249, in main
    return command.main(cmd_args)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Users\Yitzhak\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Yitzhak\\AppData\\Roaming\\Python\\Python36\\site-packages\\keras_resnet-0.0.8-py3.6.egg'
```
I checked the missing file. in fact **keras_resnet-0.0.8-py3.6.egg** is not found in the specified directory. However there is a file **keras_resnet-0.0.1-py3.6.egg**. what can be done here?

**Comment by hgaiser** [comment] 2017-11-26 22:44
Can't really help you there, and it seems this error is unrelated to `keras-retinanet`. It appears this error is caused by some issue in the setup of your python environment.

For now I'll close this issue.

**Closed by hgaiser** 2017-11-26 22:44 UTC
